# Generated by Django 6.0.4 on 2026-05-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=10)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Books', 'Books'), ('ID Card', 'ID Card'), ('Other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
